# Generated by Django 4.1.7 on 2023-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_about', models.TextField(max_length=400)),
                ('footer_about', models.TextField(max_length=200)),
                ('our_philosophy1', models.TextField()),
                ('our_philosophy2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
