# Generated by Django 4.1.7 on 2023-03-12 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPhilosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Our Philosophy', max_length=100)),
                ('our_philosophy1', models.TextField()),
                ('our_philosophy2', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='our_philosophy1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='our_philosophy2',
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='About', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
