# Generated by Django 4.1.7 on 2023-03-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_ourphilosophy_remove_about_our_philosophy1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourphilosophy',
            old_name='our_philosophy1',
            new_name='par1',
        ),
        migrations.RenameField(
            model_name='ourphilosophy',
            old_name='our_philosophy2',
            new_name='par2',
        ),
    ]
