# Generated by Django 4.1.7 on 2023-03-12 22:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_about_main_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='footer_about',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
