# Generated by Django 4.1.7 on 2023-03-12 22:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_about_footer_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='footer_about',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_about',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
