# Generated by Django 4.1.7 on 2023-03-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_about_footer_about_alter_about_main_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
            ],
        ),
    ]
