# Generated by Django 4.1.7 on 2023-03-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_embedmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedmap',
            name='source',
            field=models.CharField(max_length=600),
        ),
    ]
