# Generated by Django 4.1.7 on 2023-03-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_embedmap_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedmap',
            name='source',
            field=models.URLField(max_length=600),
        ),
    ]
