# Generated by Django 4.1.7 on 2023-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery_img1',
            field=models.ImageField(default='', upload_to='articles/gallery_img'),
        ),
        migrations.AddField(
            model_name='article',
            name='gallery_img2',
            field=models.ImageField(default='', upload_to='articles/gallery_img'),
        ),
    ]
